# Generated by Django 2.0.4 on 2019-01-04 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athlete_and_school_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sport',
            name='sports_name',
            field=models.CharField(choices=[('Baseball', 'Baseball'), ('Basketball', 'Basketball'), ('Bowling', 'Bowling'), ('Cross_Country', 'Cross Country'), ('Field_Hockey', 'Field Hockey'), ('Football', 'Football'), ('Golf', 'Golf'), ('Gymnastics', 'Gymnastics'), ('Ice_Hockey', 'Ice Hockey'), ('Soccer', 'Soccer'), ('Softball', 'Softball'), ('Swimming', 'Swimming'), ('Tennis', 'Tennis'), ('Track_And_Field', 'Track and Field'), ('Volleyball', 'Volleyball'), ('Wrestling', 'Wrestling')], max_length=45),
        ),
    ]
