# Generated by Django 2.0.4 on 2018-11-28 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0006_user_child'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='child',
        ),
    ]
