# Generated by Django 2.0.4 on 2018-11-28 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0009_auto_20181128_0940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='child',
        ),
    ]
