# Generated by Django 2.0.4 on 2019-01-21 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0012_auto_20181226_0247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='city',
        ),
    ]
