# Generated by Django 2.0.4 on 2019-01-29 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0014_friend'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friend',
            old_name='user',
            new_name='users',
        ),
    ]
