# Generated by Django 2.0.4 on 2018-10-25 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Basketball',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('position', models.CharField(choices=[('Small Forward', 'Small Forward'), ('Point Forward', 'Point Forward'), ('Point Guard', 'Point Guard'), ('Shooting Guard', 'Shooting Guard'), ('Center', 'Center'), ('Swingman', 'Swingman'), ('Point Forward', 'Point Forward'), ('Forward Center', 'Forward Center')], max_length=100)),
                ('points', models.IntegerField(default=0)),
                ('assists', models.IntegerField(default=0)),
                ('steals', models.IntegerField(default=0)),
                ('timeouts', models.IntegerField(default=0)),
            ],
        ),
    ]
