# Generated by Django 2.0.4 on 2019-01-01 21:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Baseball',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.CharField(choices=[('FRESHMAN YEAR', 'Freshman Year'), ('SOPHMORE YEAR', 'Sophmore Year'), ('JUNIOR YEAR', 'Junior Year'), ('SENIOR YEAR', 'Senior Year')], default='FRESHMAN YEAR', max_length=20)),
                ('position', models.CharField(choices=[('CATCHER', 'Catcher'), ('CENTER_FIELDER', 'Center Fielder'), ('CLOSER', 'Closer'), ('DESIGNATED_HITTER', 'Designated Hitter'), ('FIRST_BASEMAN', 'First Baseman'), ('INFIELDER', 'Infielder'), ('LEFT_FIELDER', 'Left Fielder'), ('LEFT_HANDED_SPECIALIST', 'Left-handed Specialist'), ('MIDDLE_RELIEVER', 'Middle Reliever'), ('PINCH_HITTER', 'Pinch Hitter'), ('PINCH_RUNNER', 'Pinch Runner'), ('PITCHER', 'Pitcher'), ('RELIEF_PITCHER', 'Relief Pitcher'), ('RIGHT_FIELDER', 'Right Fielder'), ('SECOND_BASEMAN', 'Second Baseman'), ('SETUP_PITCHER', 'Setup Pitcher'), ('SHORTSTOP', 'Shortstop'), ('STARTING_PITCHER', 'Starting Pitcher'), ('THIRD_BASEMAN', 'Third Baseman'), ('UTILITY_INFIELDER', 'Utility Infielder'), ('UTILITY_PLAYERS', 'Utility Players')], max_length=100)),
                ('points', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Basketball',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.CharField(choices=[('FRESHMAN YEAR', 'Freshman Year'), ('SOPHMORE YEAR', 'Sophmore Year'), ('JUNIOR YEAR', 'Junior Year'), ('SENIOR YEAR', 'Senior Year')], default='FRESHMAN YEAR', max_length=20)),
                ('position', models.CharField(choices=[('SMALL_FORWARD', 'Small Forward'), ('POINT_FORWARD', 'Point Forward'), ('POINT_GUARD', 'Point Guard'), ('SHOOTING_GUARD', 'Shooting Guard'), ('CENTER', 'Center'), ('WING', 'Wing'), ('POINT_FORWARD', 'Point Forward'), ('FORWARD_CENTER', 'Forward Center')], max_length=30)),
                ('points', models.IntegerField(default=0)),
                ('assists', models.IntegerField(default=0)),
                ('steals', models.IntegerField(default=0)),
                ('timeouts', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bowling',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.CharField(choices=[('FRESHMAN YEAR', 'Freshman Year'), ('SOPHMORE YEAR', 'Sophmore Year'), ('JUNIOR YEAR', 'Junior Year'), ('SENIOR YEAR', 'Senior Year')], default='FRESHMAN YEAR', max_length=20)),
                ('position', models.CharField(choices=[('LEFT_HANDED', 'Left-handed'), ('RIGHT_HANDED', 'Right-handed')], max_length=30)),
                ('points', models.IntegerField(default=0)),
                ('assists', models.IntegerField(default=0)),
                ('steals', models.IntegerField(default=0)),
                ('timeouts', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cross_Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Field_Hockey',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.CharField(choices=[('FRESHMAN YEAR', 'Freshman Year'), ('SOPHMORE YEAR', 'Sophmore Year'), ('JUNIOR YEAR', 'Junior Year'), ('SENIOR YEAR', 'Senior Year')], default='FRESHMAN YEAR', max_length=20)),
                ('position', models.CharField(choices=[('CENTER', 'Left-handed'), ('DEFENSEMAN', 'Right-handed'), ('GOALIE', 'Left-handed'), ('LEFT_WING', 'Left-handed'), ('RIGHT_WING', 'Left-handed')], max_length=30)),
                ('points', models.IntegerField(default=0)),
                ('assists', models.IntegerField(default=0)),
                ('steals', models.IntegerField(default=0)),
                ('timeouts', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Football',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.CharField(choices=[('FRESHMAN YEAR', 'Freshman Year'), ('SOPHMORE YEAR', 'Sophmore Year'), ('JUNIOR YEAR', 'Junior Year'), ('SENIOR YEAR', 'Senior Year')], default='FRESHMAN YEAR', max_length=20)),
                ('position', models.CharField(choices=[('CENTER', 'Left-handed'), ('CORNERBACK', 'Right-handed'), ('DEFENSIVE_END', 'Left-handed'), ('DEFENSIVE_TACKLE', 'Left-handed'), ('DIMEBACK', 'Left-handed'), ('GUNNER', 'Left-handed'), ('HOLDER', 'Left-handed'), ('JAMMER', 'Left-handed'), ('KICK_RETURNER', 'Left-handed'), ('KICKER', 'Left-handed'), ('KICKOFF_RETURNER', 'Left-handed'), ('LONG_SNAPPER', 'Left-handed'), ('MIDDLE_LINEBACK', 'Left-handed'), ('NICKLEBACK', 'Left-handed'), ('OFFENSIVE_GUARD', 'Left-handed'), ('OFFENSIVE_TACKLE', 'Left-handed'), ('PUNTER', 'Left-handed'), ('RUNNING_BACK', 'Left-handed'), ('SAFETY', 'Left-handed'), ('TIGHT_END', 'Left-handed'), ('UPBACK', 'Left-handed'), ('WIDE_RECEIVER', 'Left-handed')], max_length=30)),
                ('points', models.IntegerField(default=0)),
                ('assists', models.IntegerField(default=0)),
                ('steals', models.IntegerField(default=0)),
                ('timeouts', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Golf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Gymnastics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Ice_Hockey',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.CharField(choices=[('FRESHMAN YEAR', 'Freshman Year'), ('SOPHMORE YEAR', 'Sophmore Year'), ('JUNIOR YEAR', 'Junior Year'), ('SENIOR YEAR', 'Senior Year')], default='FRESHMAN YEAR', max_length=20)),
                ('position', models.CharField(choices=[('CENTER', 'Left-handed'), ('GOALIE', 'Right-handed'), ('LEFT_DEFENDER', 'Right-handed'), ('LEFT_WING', 'Right-handed'), ('RIGHT_DEFENDER', 'Right-handed'), ('RIGHT_WING', 'Right-handed')], max_length=30)),
                ('points', models.IntegerField(default=0)),
                ('assists', models.IntegerField(default=0)),
                ('steals', models.IntegerField(default=0)),
                ('timeouts', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Soccer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.CharField(choices=[('FRESHMAN YEAR', 'Freshman Year'), ('SOPHMORE YEAR', 'Sophmore Year'), ('JUNIOR YEAR', 'Junior Year'), ('SENIOR YEAR', 'Senior Year')], default='FRESHMAN YEAR', max_length=20)),
                ('position', models.CharField(choices=[('ATTACKING_MIDFIELDER', 'Attacking Midfielder'), ('CENTER_BACK', 'Center Back'), ('CENTER_FORWARD', 'Center Forward'), ('CENTER_MIDFIELDER', 'Center Midfielder'), ('DEFENSIVE_MIDFIELDER', 'Defensive Midfielder'), ('FULLBACK', 'Fullback'), ('GOALKEEPER', 'Goalkeeper'), ('LEFT_MIDFIELDER', 'Left Midfielder'), ('RIGHT_MIDFIELDER', 'Right Midfielder'), ('SECOND_STRIKER', 'Second Striker'), ('SWEEPER', 'Sweeper'), ('STRIKER', 'Striker'), ('WINGER', 'Winger')], max_length=100)),
                ('points', models.IntegerField(default=0)),
                ('assists', models.IntegerField(default=0)),
                ('steals', models.IntegerField(default=0)),
                ('timeouts', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Softball',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.CharField(choices=[('FRESHMAN YEAR', 'Freshman Year'), ('SOPHMORE YEAR', 'Sophmore Year'), ('JUNIOR YEAR', 'Junior Year'), ('SENIOR YEAR', 'Senior Year')], default='FRESHMAN YEAR', max_length=20)),
                ('position', models.CharField(choices=[('BATTER', 'Left-handed'), ('CATCHER', 'Right-handed'), ('FIRST_BASEMAN', 'Stopper'), ('OUTFIELDER', 'Stopper'), ('PITCHER', 'Stopper'), ('SECOND_BASEMAN', 'Stopper'), ('SHORTSTOP', 'Stopper'), ('THIRD_BASEMAN', 'Stopper')], max_length=30)),
                ('points', models.IntegerField(default=0)),
                ('assists', models.IntegerField(default=0)),
                ('steals', models.IntegerField(default=0)),
                ('timeouts', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Swimming',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.CharField(choices=[('FRESHMAN YEAR', 'Freshman Year'), ('SOPHMORE YEAR', 'Sophmore Year'), ('JUNIOR YEAR', 'Junior Year'), ('SENIOR YEAR', 'Senior Year')], default='FRESHMAN YEAR', max_length=20)),
                ('freestyle_50', models.IntegerField(default=0)),
                ('backstroke_100', models.IntegerField(default=0)),
                ('breaststroke_100', models.IntegerField(default=0)),
                ('butterfly_100', models.IntegerField(default=0)),
                ('freestyle_100', models.IntegerField(default=0)),
                ('free_relay_200', models.IntegerField(default=0)),
                ('freestyle_200', models.IntegerField(default=0)),
                ('individual_medley_200', models.IntegerField(default=0)),
                ('free_relay_400', models.IntegerField(default=0)),
                ('freestyle_500', models.IntegerField(default=0)),
                ('points', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tennis',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.CharField(choices=[('FRESHMAN YEAR', 'Freshman Year'), ('SOPHMORE YEAR', 'Sophmore Year'), ('JUNIOR YEAR', 'Junior Year'), ('SENIOR YEAR', 'Senior Year')], default='FRESHMAN YEAR', max_length=20)),
                ('games_won', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Track_And_Field',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.CharField(choices=[('FRESHMAN YEAR', 'Freshman Year'), ('SOPHMORE YEAR', 'Sophmore Year'), ('JUNIOR YEAR', 'Junior Year'), ('SENIOR YEAR', 'Senior Year')], default='FRESHMAN YEAR', max_length=20)),
                ('sprint_100_games', models.IntegerField(default=0)),
                ('sprint_100_average', models.DecimalField(decimal_places=3, default=0, max_digits=6)),
                ('sprint_200_games', models.IntegerField(default=0)),
                ('sprint_200_average', models.DecimalField(decimal_places=3, default=0, max_digits=6)),
                ('sprint_400_games', models.IntegerField(default=0)),
                ('sprint_400_average', models.DecimalField(decimal_places=3, default=0, max_digits=6)),
                ('hurdles_100_games', models.IntegerField(default=0)),
                ('hurdles_100_average', models.DecimalField(decimal_places=3, default=0, max_digits=6)),
                ('hurdles_110_games', models.IntegerField(default=0)),
                ('hurdles_110_average', models.DecimalField(decimal_places=3, default=0, max_digits=6)),
                ('hurdles_400_games', models.IntegerField(default=0)),
                ('hurdles_400_average', models.DecimalField(decimal_places=3, default=0, max_digits=7)),
                ('middle_distance_800_games', models.IntegerField(default=0)),
                ('middle_distance_800_average', models.DecimalField(decimal_places=3, default=0, max_digits=7)),
                ('middle_distance_1500_games', models.IntegerField(default=0)),
                ('middle_distance_1500_average', models.DecimalField(decimal_places=3, default=0, max_digits=7)),
                ('long_distance_3000_games', models.IntegerField(default=0)),
                ('long_distance_3000_average', models.DecimalField(decimal_places=3, default=0, max_digits=8)),
                ('long_distance_5000_games', models.IntegerField(default=0)),
                ('long_distance_5000_average', models.DecimalField(decimal_places=3, default=0, max_digits=8)),
                ('long_distance_10000_games', models.IntegerField(default=0)),
                ('long_distance_10000_average', models.DecimalField(decimal_places=3, default=0, max_digits=8)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Volleyball',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.CharField(choices=[('FRESHMAN YEAR', 'Freshman Year'), ('SOPHMORE YEAR', 'Sophmore Year'), ('JUNIOR YEAR', 'Junior Year'), ('SENIOR YEAR', 'Senior Year')], default='FRESHMAN YEAR', max_length=20)),
                ('position', models.CharField(choices=[('LEFT_HANDED', 'Left-handed'), ('RIGHT_HANDED', 'Right-handed')], max_length=30)),
                ('points', models.IntegerField(default=0)),
                ('assists', models.IntegerField(default=0)),
                ('steals', models.IntegerField(default=0)),
                ('timeouts', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Wrestling',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.CharField(choices=[('FRESHMAN YEAR', 'Freshman Year'), ('SOPHMORE YEAR', 'Sophmore Year'), ('JUNIOR YEAR', 'Junior Year'), ('SENIOR YEAR', 'Senior Year')], default='FRESHMAN YEAR', max_length=20)),
                ('position', models.CharField(choices=[('LEFT_HANDED', 'Left-handed'), ('RIGHT_HANDED', 'Right-handed')], max_length=30)),
                ('points', models.IntegerField(default=0)),
                ('assists', models.IntegerField(default=0)),
                ('steals', models.IntegerField(default=0)),
                ('timeouts', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='wrestling',
            unique_together={('year', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='volleyball',
            unique_together={('year', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='track_and_field',
            unique_together={('year', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='tennis',
            unique_together={('year', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='swimming',
            unique_together={('year', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='softball',
            unique_together={('year', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='soccer',
            unique_together={('year', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='ice_hockey',
            unique_together={('year', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='football',
            unique_together={('year', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='field_hockey',
            unique_together={('year', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='bowling',
            unique_together={('year', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='basketball',
            unique_together={('year', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='baseball',
            unique_together={('year', 'user')},
        ),
    ]
