# Generated by Django 2.0.4 on 2019-01-03 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_map_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cheerleading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
