# Generated by Django 2.0.4 on 2018-11-11 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_map_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Basketball',
        ),
    ]
