# Generated by Django 2.0.4 on 2019-01-10 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_map_app', '0002_cheerleading'),
    ]

    operations = [
        migrations.RenameField(
            model_name='baseball',
            old_name='points',
            new_name='bases_on_ball',
        ),
        migrations.AddField(
            model_name='baseball',
            name='double_hits',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='baseball',
            name='games',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='baseball',
            name='home_runs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='baseball',
            name='runs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='baseball',
            name='runs_batted_in',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='baseball',
            name='single_hits',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='baseball',
            name='steals',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='baseball',
            name='strikeouts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='baseball',
            name='tripple_hits',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='baseball',
            name='position',
            field=models.CharField(choices=[('C', 'Catcher'), ('CF', 'Center Fielder'), ('CL', 'Closer'), ('DH', 'Designated Hitter'), ('1B', 'First Baseman'), ('IF', 'Infielder'), ('LF', 'Left Fielder'), ('LHS', 'Left-handed Specialist'), ('P', 'Pitcher'), ('RF', 'Right Fielder'), ('2B', 'Second Baseman'), ('SS', 'Shortstop'), ('SP', 'Starting Pitcher'), ('3B', 'Third Baseman'), ('UI', 'Utility Infielder'), ('UP', 'Utility Players')], max_length=100),
        ),
        migrations.AlterField(
            model_name='baseball',
            name='year',
            field=models.CharField(choices=[('FRESHMAN', 'Freshman Year'), ('SOPHMORE', 'Sophmore Year'), ('JUNIOR', 'Junior Year'), ('SENIOR', 'Senior Year')], default='FRESHMAN', max_length=20),
        ),
    ]
