# Generated by Django 2.0.4 on 2018-11-12 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_map_app', '0003_basketball'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basketball',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
