# Generated by Django 2.0.4 on 2019-01-10 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_map_app', '0003_auto_20190110_0254'),
    ]

    operations = [
        migrations.RenameField(
            model_name='baseball',
            old_name='steals',
            new_name='stolen_bases',
        ),
    ]
