# Generated by Django 2.0.4 on 2018-11-12 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_map_app', '0004_auto_20181112_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basketball',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
