# Generated by Django 2.0.4 on 2019-01-14 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_map_app', '0004_auto_20190110_0306'),
    ]

    operations = [
        migrations.AddField(
            model_name='basketball',
            name='dunks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='basketball',
            name='three_pointers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='basketball',
            name='two_pointers',
            field=models.IntegerField(default=0),
        ),
    ]
