# Generated by Django 2.0.4 on 2019-01-14 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_map_app', '0005_auto_20190114_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basketball',
            name='position',
            field=models.CharField(choices=[('SF', 'Small Forward'), ('PF', 'Point Forward'), ('PG', 'Point Guard'), ('SG', 'Shooting Guard'), ('C', 'Center'), ('W', 'Wing'), ('PF', 'Point Forward'), ('FC', 'Forward Center')], max_length=30),
        ),
    ]
