# Generated by Django 2.0.4 on 2018-11-28 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_map_app', '0005_auto_20181112_0959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basketball',
            name='user',
        ),
        migrations.DeleteModel(
            name='Basketball',
        ),
    ]
