# Generated by Django 2.0.4 on 2019-01-16 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_map_app', '0006_auto_20190114_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basketball',
            name='year',
            field=models.CharField(choices=[('FRESHMAN', 'Freshman Year'), ('SOPHMORE', 'Sophmore Year'), ('JUNIOR', 'Junior Year'), ('SENIOR', 'Senior Year')], default='FRESHMAN', max_length=20),
        ),
    ]
