# Generated by Django 2.0.4 on 2018-11-28 14:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_map_app', '0007_basketball'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basketball',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user_sport', to=settings.AUTH_USER_MODEL),
        ),
    ]
