# Generated by Django 2.0.4 on 2018-12-03 14:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_map_app', '0008_auto_20181128_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basketball',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_sport', to=settings.AUTH_USER_MODEL),
        ),
    ]
