# Generated by Django 2.0.4 on 2018-12-03 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_map_app', '0009_auto_20181203_0950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basketball',
            name='user',
        ),
        migrations.DeleteModel(
            name='Basketball',
        ),
    ]
