# Generated by Django 2.0.4 on 2018-12-08 14:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('student_map_app', '0010_auto_20181203_0953'),
    ]

    operations = [
        migrations.CreateModel(
            name='Basketball',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('position', models.CharField(choices=[('Small Forward', 'Small Forward'), ('Point Forward', 'Point Forward'), ('Point Guard', 'Point Guard'), ('Shooting Guard', 'Shooting Guard'), ('Center', 'Center'), ('Swingman', 'Swingman'), ('Point Forward', 'Point Forward'), ('Forward Center', 'Forward Center')], max_length=100)),
                ('points', models.IntegerField(default=0)),
                ('assists', models.IntegerField(default=0)),
                ('steals', models.IntegerField(default=0)),
                ('timeouts', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_sport', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
