# Generated by Django 2.0.4 on 2018-12-22 00:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('school_name', models.CharField(max_length=100)),
                ('school_address', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'School',
                'verbose_name_plural': 'Schools',
            },
        ),
        migrations.CreateModel(
            name='School_Sport',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ss_school_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ss_school_id', to='scholarship_map.School')),
            ],
            options={
                'verbose_name': 'School_Sport',
                'verbose_name_plural': 'School_Sports',
            },
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.AutoField(default=None, primary_key=True, serialize=False)),
                ('sports_name', models.IntegerField(choices=[(1, 'Baseball'), (2, 'Basketball'), (3, 'Bowling'), (4, 'Cheerleading'), (5, 'Cross Country'), (6, 'Dance Team'), (7, 'Football'), (8, 'Golf'), (9, 'Gymnastics'), (10, 'Hockey'), (11, 'Soccer'), (12, 'Softball'), (13, 'Swimming'), (14, 'Tennis'), (15, 'Track & Field'), (16, 'Volleyball'), (17, 'Wrestling')])),
            ],
            options={
                'verbose_name': 'Sport',
                'verbose_name_plural': 'Sports',
            },
        ),
        migrations.CreateModel(
            name='User_School',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('school_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='scholarship_map.School_Sport')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_school_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User_School',
                'verbose_name_plural': 'User_Schools',
            },
        ),
        migrations.CreateModel(
            name='User_Sport',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sports_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usersports_sports_id', to='scholarship_map.Sport')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usersports_student_id', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User_Sport',
                'verbose_name_plural': 'User_Sports',
            },
        ),
        migrations.AddField(
            model_name='school_sport',
            name='ss_sports_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ss_sports_id', to='scholarship_map.Sport'),
        ),
        migrations.AlterUniqueTogether(
            name='user_sport',
            unique_together={('student_id', 'sports_id')},
        ),
        migrations.AlterUniqueTogether(
            name='user_school',
            unique_together={('student_id', 'school_id')},
        ),
        migrations.AlterUniqueTogether(
            name='school_sport',
            unique_together={('ss_school_id', 'ss_sports_id')},
        ),
    ]
