# Generated by Django 2.0.4 on 2018-12-22 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship_map', '0002_auto_20181221_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sport',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sport',
            name='sports_name',
            field=models.CharField(choices=[(1, 'Baseball'), (2, 'Basketball'), (3, 'Bowling'), (4, 'Cheerleading'), (5, 'Cross Country'), (6, 'Dance Team'), (7, 'Football'), (8, 'Golf'), (9, 'Gymnastics'), (10, 'Hockey'), (11, 'Soccer'), (12, 'Softball'), (13, 'Swimming'), (14, 'Tennis'), (15, 'Track & Field'), (16, 'Volleyball'), (17, 'Wrestling')], max_length=40),
        ),
    ]
