# Generated by Django 2.0.4 on 2018-12-22 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship_map', '0003_auto_20181221_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sport',
            name='sports_name',
            field=models.CharField(choices=[('BASEBALL', 'Baseball'), ('BASKETBALL', 'Basketball'), ('BOWLING', 'Bowling'), ('CHEERLEADING', 'Cheerleading'), ('CROSS COUNTRY', 'Cross Country'), ('DANCE TEAM', 'Dance Team'), ('FOOTBALL', 'Football'), ('GOLF', 'Golf'), ('GYMNASTICS', 'Gymnastics'), ('HOCKEY', 'Hockey'), ('SOCCER', 'Soccer'), ('SOFTBALL', 'Softball'), ('SWIMMING', 'Swimming'), ('TENNIS', 'Tennis'), ('TRACK AND FIELD', 'Track and Field'), ('VOLLEYBALL', 'Volleyball'), ('WRESTLING', 'Wrestling')], max_length=45),
        ),
    ]
