# Generated by Django 2.0.4 on 2018-12-22 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship_map', '0004_auto_20181221_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_school',
            name='school_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='scholarship_map.School'),
        ),
    ]
