# Generated by Django 2.0.4 on 2018-10-13 05:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scholarship_map', '0005_auto_20180623_2335'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Schools',
            new_name='School',
        ),
        migrations.RenameModel(
            old_name='School_Sports',
            new_name='School_Sport',
        ),
        migrations.RenameModel(
            old_name='Sports',
            new_name='Sport',
        ),
        migrations.RenameModel(
            old_name='Sport_Stats',
            new_name='Sport_Stat',
        ),
        migrations.RenameModel(
            old_name='User_Schools',
            new_name='User_School',
        ),
        migrations.RenameModel(
            old_name='User_Sports',
            new_name='User_Sport',
        ),
        migrations.AlterModelOptions(
            name='school',
            options={'verbose_name': 'School', 'verbose_name_plural': 'Schools'},
        ),
        migrations.AlterModelOptions(
            name='school_sport',
            options={'verbose_name': 'School_Sport', 'verbose_name_plural': 'School_Sports'},
        ),
        migrations.AlterModelOptions(
            name='sport',
            options={'verbose_name': 'Sport', 'verbose_name_plural': 'Sports'},
        ),
        migrations.AlterModelOptions(
            name='sport_stat',
            options={'verbose_name': 'Sport_Stat', 'verbose_name_plural': 'Sports_Stats'},
        ),
        migrations.AlterModelOptions(
            name='user_school',
            options={'verbose_name': 'User_School', 'verbose_name_plural': 'User_Schools'},
        ),
        migrations.AlterModelOptions(
            name='user_sport',
            options={'verbose_name': 'User_Sport', 'verbose_name_plural': 'User_Sports'},
        ),
    ]
