# Generated by Django 2.0.4 on 2018-12-23 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship_map', '0005_auto_20181221_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school_sport',
            name='ss_school_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rn_school_schoolsport', to='scholarship_map.School'),
        ),
        migrations.AlterField(
            model_name='school_sport',
            name='ss_sports_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rn_sport_schoolsport', to='scholarship_map.Sport'),
        ),
    ]
