# Generated by Django 2.0.4 on 2018-10-18 16:51

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scholarship_map', '0006_auto_20181013_0147'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_school',
            old_name='unique_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='user_school',
            old_name='student_school_id',
            new_name='school_id',
        ),
        migrations.AlterUniqueTogether(
            name='user_school',
            unique_together={('student_id', 'school_id')},
        ),
    ]
