# Generated by Django 2.0.4 on 2018-10-19 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship_map', '0007_auto_20181018_1251'),
    ]

    operations = [
        migrations.RenameField(
            model_name='school',
            old_name='school_id',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='school',
            name='school_name',
            field=models.CharField(max_length=100),
        ),
    ]
