# Generated by Django 2.0.4 on 2018-10-25 18:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship_map', '0008_auto_20181019_1137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school_sport',
            name='unique_id',
        ),
        migrations.RemoveField(
            model_name='user_school',
            name='id',
        ),
        migrations.AlterField(
            model_name='school_sport',
            name='ss_school_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='ss_school_id', serialize=False, to='scholarship_map.School'),
        ),
        migrations.AlterField(
            model_name='user_school',
            name='school_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_school_id', to='scholarship_map.School_Sport'),
        ),
        migrations.AlterField(
            model_name='user_school',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='user_school_student_id', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
