# Generated by Django 2.0.4 on 2018-10-25 21:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship_map', '0009_auto_20181025_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='school_sport',
            name='unique_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_school',
            name='id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='school_sport',
            name='ss_school_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ss_school_id', to='scholarship_map.School'),
        ),
        migrations.AlterField(
            model_name='user_school',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_school_student_id', to=settings.AUTH_USER_MODEL),
        ),
    ]
