# Generated by Django 2.0.4 on 2018-10-25 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship_map', '0010_auto_20181025_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sport',
            name='sports_name',
            field=models.IntegerField(choices=[(1, 'Baseball'), (2, 'Basketball'), (3, 'Bowling'), (4, 'Cheerleading'), (5, 'Cross Country'), (6, 'Dance Team'), (7, 'Football'), (8, 'Golf'), (9, 'Gymnastics'), (10, 'Hockey'), (11, 'Soccer'), (12, 'Softball'), (13, 'Swimming'), (14, 'Tennis'), (15, 'Track & Field'), (16, 'Volleyball'), (17, 'Wrestling')], default=1, unique=True),
        ),
    ]
